export const roadmapMarkdown = `
| Priority | Task                             | Category                                  | Description                                                                                           | Value                   |
|----------|----------------------------------|-------------------------------------------|-------------------------------------------------------------------------------------------------------------------|-------------------------|
| 🚩P0     | Scroll-to-bottom reliability     | Usability & UX                            | Ensure scrolling always snaps to newest message unless user has scrolled up.                          | Usability               |
| 🚩P0     | Auto-scroll control              | Usability & UX                            | Pause scroll when user is reviewing; show jump-to-bottom if new messages arrive.                      | UX polish               |
| ⚠️P1     | Typing indicator                 | Usability & UX                            | Show animated indicator while assistant is generating.                                                | Feedback loop           |
| ⚠️P1     | Multiline message input          | Usability & UX                            | Allow users to type multi-line messages easily.                                                       | Usability               |
| ⚠️P1     | User personas                    | Prompt Engineering + Style Control        | Support system prompt injection for assistant personality presets.                                   | Tone control            |
| ⚠️P1     | Message editing                  | Usability & UX                            | Let users edit and resend their own messages.                                                         | Flexibility             |
| ⚠️P1     | Message deletion                 | Usability & UX                            | Let users remove messages from history.                                                               | Control                 |
| ⚠️P1     | Chat export (JSON/txt)           | Interface SDK                             | Allow export of chat to file.                                                                         | Data portability        |
| ⚠️P1     | Compare config diff view         | Evaluation + Analysis                     | Highlight config differences in Compare tab.                                                          | Clarity                 |
| ⚠️P1     | Compare prompt A/B testing       | Evaluation + Analysis                     | Run a prompt through two configs and return both outputs.                                             | Evaluation              |
| ⚠️P1     | Compare performance insight      | Evaluation + Analysis                     | Show token count, latency, entropy for each model run.                                                | Feedback                |
| ⚠️P1     | Config save/load/export          | Interface SDK                             | Allow users to save, load, and export tuning configs.                                                 | Efficiency              |
| ⚠️P1     | Dark mode support                | Usability & UX                            | Provide toggle or auto-dark theme.                                                                    | Accessibility           |
| 🍀P2     | Multi-language support           | Internationalization                      | Localize app UI and prompts.                                                                          | Internationalization    |
| 🍀P2     | User authentication              | System Design & Stability                 | Support login system if needed for future backend sync.                                               | Security                |
| 🍀P2     | Rate limiting                    | System Design & Stability                 | Add limits per user/session to prevent overload.                                                      | Abuse prevention        |
| 🍀P2     | Analytics dashboard              | Evaluation + Analysis                     | Track usage metrics and user behavior (locally or securely).                                          | Insight                 |
| 🍀P2     | Plugin integrations              | Developer Tooling                         | Allow third-party plugins to extend app capabilities.                                                 | Extensibility           |
| 🍀P2     | Voice input                      | Usability & UX                            | Add speech-to-text message input.                                                                     | Accessibility           |
| 🍀P2     | Message reactions                | Usability & UX                            | Add emoji-based reactions to assistant/user messages.                                                 | Engagement              |
| 🍀P2     | Offline mode                     | Usability & UX                            | Let users write and save messages offline, sync later.                                                | Mobility                |
| 🍀P2     | Prompt test suite                | Evaluation + Analysis                     | Add framework to test a batch of prompts across configs/models.                                       | Reliability             |
| 🍀P2     | Chat comparison history          | Evaluation + Analysis                     | Show side-by-side chats from multiple models/configs.                                                 | Evaluation              |
`;